# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    groups:
      strapi:
        patterns:
          - "@strapi*"
          - "strapi*"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-router-dom"
      - dependency-name: "styled-components"
      # Those 3 dependencies are used by strapi v4.15.0 and above and can only be upgraded when strapi is ready for it.
    assignees:
      - "onissen"
    labels:
      - "dependencies"
    commit-message:
      prefix: "npm"
      include: "scope"
